Document: amxa-puavo-os-art
Title: Debian amxa-puavo-os-art Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-puavo-os-art is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-puavo-os-art/amxa-puavo-os-art.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-puavo-os-art/amxa-puavo-os-art.ps.gz

Format: text
Files: /usr/share/doc/amxa-puavo-os-art/amxa-puavo-os-art.text.gz

Format: HTML
Index: /usr/share/doc/amxa-puavo-os-art/html/index.html
Files: /usr/share/doc/amxa-puavo-os-art/html/*.html
